# Generated by Django 2.0.9 on 2019-05-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatter', '0002_auto_20190524_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
